server:
  port: 8081




woconnect:
  ip: 192.168.145.201
  timeout: 1000
  pingtimes: 10
  host: 192.168.145.233
  port: 22
  username: root
  password: 123123




spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/pingtest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true